### ISSUE TITLE
Localstorage write quota frequently exceeded

### ISSUE THREAD

**Issue by jackrwoods** [OSU-Sustainability-Office/energy-dashboard#119]
If you open a dashboard for any building (for example, Arnold: https://dashboard.sustainability.oregonstate.edu/#/building/14/2), you will see a message printed to the Firefox Developer Tools console: `DOMException: The quota has been exceeded. data_store.js:147:8`. This error message indicates that Firefox's localStorage write quota has been exceeded (too many writes to the persistent cache in a short amount of time).

The new persistent data cache uses [Local Storage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) to store a "stringified" JSON object containing all of the cached meter data. This is performed on [data_store.js:145](https://github.com/OSU-Sustainability-Office/energy-dashboard/blob/master/src/store/data_layer/data_store.js#L145). This is called whenever new data is added to the cache.

I *suspect* the issue is caused by incorrectly calculating what data already exists within the cache. If you reload the page and watch the "XHR" tab of the "Network" tab in the Firefox developer tools, you will observe an API call for exactly 15 minutes of data: `startDate=1602783000&endDate=1608054300` (the linux epoch timestamps may change for you depending on when you access the page). Although the data already exists in the cache, the cache erroneously believes this data is not present. This causes extraneous API calls, which result in extraneous writes to localStorage, which results in exceeding the localStorage write quota.

If this is the case, a fix will probably require:
    - Some sort of de-duping or timeout mechanism, limiting successive localStorage writes
    - Modifying how interval boundaries are calculated in the cache. How does the cache calculate what data is already present?

**Comment by MilanDonhowe** [comment]
I had some trouble re-creating the write quota error on my end locally--one potential cause could be that since localStorage is persistent beyond sessions (and typically browser/computer restarts) so it's just continuously accumulating queried data which might not be accessed again by the user.  This is compounded by the fact localStorage has only a moderate amount of space ([about 10mb per site for most browsers but can vary](https://en.wikipedia.org/wiki/Web_storage#Features)) 

I created a branch `localStorageQuota` to address this issue, right all I've done is switch over to the [session storage API ](https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage) which has an identical interface but isn't persistent across different user sessions (this is potentially problematic see question below).  I haven't figured out what's causing the extraneous GET requests but it's probably the bounds error you mentioned in the issue text.  I will also try to address this before making a PR.

**Do we want the data cache to persist beyond user sessions? (e.g. across browser restarts)** If we do, it might make sense to move the data_layer to use the [IndexedDB API over local or session storage](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API) since it is intended for storing large amounts of structured data.  Or alternatively we could just implement some mechanism to "clear out" old data in localStorage.

**Comment by jackrwoods** [comment]
@MilanDonhowe We want the data to be cached between browser restarts. I think the IndexedDB solution is a great idea.

Essentially, the VueX store caches data during a user's session. The persistent cache should enable frequent dashboard users to access data faster than if they had to re-download it each time.
