### ISSUE TITLE
Refactor campaigns

### ISSUE THREAD

**Issue by MilanDonhowe** [OSU-Sustainability-Office/energy-dashboard#191]
Campaigns feature has significant issues.

- [x] Create Test Campaign
- [x] Non-robust to missing data (won't easily show errors)
- [x] Unable to support manually entered data into DB for buildings without Acquisuite support
- [x] Math may need auditing for accuracy
- [ ] Charts & leader-board hard to read.

Need to fix these issues prior to Spring.

**Comment by solderq35** [comment]
After inserting a test campaign in https://dashboard.sustainability.oregonstate.edu/#/campaign/9, here are some bugs I noticed:

### Data Timing Issues
- The "past X days" tab seems to retrieve data as defined by `compare_start` and not `date_start`
  - The "past X days" tab is retrieving data from 2022
  - Reference Image from Browser Debug: ![network](https://media.discordapp.net/attachments/1051648008594391077/1066061110177968218/image.png?width=1440&height=649)
  - [This API URL](https://api.sustainability.oregonstate.edu/v2/energy/data?id=120&startDate=1646117100&endDate=1647586800&point=accumulated_real&meterClass=4045) from the above browser debug window shows Unix timestamps ([reference](https://www.unixtimestamp.com/index.php)) of February 28, 2022 to March 18, 2022
  - Reference image for `compare_start` and `date_start` from SQL database: ![image](https://user-images.githubusercontent.com/82061589/213784295-fcfdbb6b-6152-4003-bbcd-d3237cf6cb40.png)
  - I think [the code at this URL](https://github.com/OSU-Sustainability-Office/energy-dashboard/blob/9064080006131be18888c36085cd7909cc258215/src/components/map/time_switch_buttons_big.vue#L139) is responsible. Again, the "past 6 hours" and "past day" seems to retrieve 2023 data, but not past X days


### Weatherford / ILLC
- Weatherford and ILLC (which seem to be the buildings where we insert data manually in SQL) have some bugs too.
- Weatherford and ILLC don't show up on the tabs on the left until you hover mouse over them. They show up as a block of solid white until then.
- Upon clicking on ILLC at the bottom of the list of buildings on the left, it teleports to the top. And vice versa with Weatherford, which teleports to the bottom.
- Percentage of energy savings? is shown as NaN on both Weatherford and ILLC

**Comment by solderq35** [comment]
# Weatherford Debugging

**Intent: Debug why Weatherford Hall shows no data for "Current Usage" on the campaigns page. The "Baseline" value for Weatherford is calculated just fine, but not the "Current Usage".**

## Procedure

- Edit [env.env.development](https://github.com/OSU-Sustainability-Office/energy-dashboard/blob/master/.env.development) to use the production version of the backend, for faster frontend (Vue Store) debugging.
```
VUE_APP_ROOT_API=https://api.sustainability.oregonstate.edu/v2/energy
VUE_APP_HOST_ADDRESS=http://localhost:8080
```
- Use http://localhost:8080/#/campaign/11 (test campaign for just Weatherford, with 2022 timestamps for testing). This will ensure all the data only comes from Weatherford for easier debugging. Campaign 11 is found in "Past Campaigns" tab.
  - The test campaign 11 may be closed in the future, in which case use http://localhost:8080/#/campaign/8 (2022 campaign)
- Insert `console.log(resultDataObject)` after line 37 in [src/store/chart_modifiers/line_bar/accumulated_real.js](https://github.com/OSU-Sustainability-Office/energy-dashboard/blob/master/src/store/chart_modifiers/line_bar/accumulated_real.js#L37)
  -  This lets you see the array for "Current Usage" data.
  - Alternatively, you can insert  `console.log(chartData.data)` after line 53 in [src/store/chart_module.js](https://github.com/OSU-Sustainability-Office/energy-dashboard/blob/master/src/store/chart.module.js#L53). This will show you both the "Current Usage" and "Baseline" data arrays.
- Insert `console.log(i + delta + ' i + delta')` before line 70 of [src/store/chart_modifiers/line_bar/accumulated_real.js](https://github.com/OSU-Sustainability-Office/energy-dashboard/blob/master/src/store/chart_modifiers/line_bar/accumulated_real.js#L70)
  - This will show you the "key" value to the `resultDataObject`'s [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) data structure.
 - Insert `console.log(resultDataObject.get(1649314800) + ' weatherford with hardcoded correct value')` before line 70 of [src/store/chart_modifiers/line_bar/accumulated_real.js](https://github.com/OSU-Sustainability-Office/energy-dashboard/blob/master/src/store/chart_modifiers/line_bar/accumulated_real.js#L70)
   - The value `1649314800` is a key value we got from `console.log(resultDataObject)` after line 37 in the accumulated_real.js file 
- Insert `console.log(resultDataObject.get(1649199600) + ' weatherford with i + delta value')` ` before line 70 of [src/store/chart_modifiers/line_bar/accumulated_real.js](https://github.com/OSU-Sustainability-Office/energy-dashboard/blob/master/src/store/chart_modifiers/line_bar/accumulated_real.js#L70)
  - The value `1649199600` is one of the values we got from `console.log(i + delta + ' i + delta')` before line 70 in the accumulated_real.js file

## Results / Analysis
![image](https://user-images.githubusercontent.com/82061589/216463537-58f577ba-ca28-4a45-99a9-c0b46ee6c421.png)

- The calculated `i + delta` key value for the `resultDataObject` Map are resulting in invalid key values, hence `undefined weatherford with i + delta value` in the browser debug window.
- Only Weatherford Hall (out of the buildings in campaign 8) has this issue here because we manually inserted data for Weatherford, with gaps bigger than 15 minutes between data points.
- Other buildings have data for each 15 minutes (or nearly so), avoiding invalid key values for `resultDataObject`
- The output of `4438 weatherford with hardcoded correct value` in browser debug window confirms that the `resultDataObject` map returns valid data for Weatherford assuming a valid key value is provided.

## Possible Solutions
- Somehow "round" the `i + delta` key value for Weatherford to the nearest **valid** key (nearest time-wise, referencing [Unix Timestamps](https://www.unixtimestamp.com/index.php))
- Give up on Map / Key for this and switch the `resultDataObject` for Weatherford or all buildings to use an array with an index instead (may cause issues in the future if we ever perform any deletions in the database)
- If the graph stuff in `accumulated_baseline.js` can't be fixed in time for the 2023 campaign, then look into a better way of integrating the [backup ranking repo's code](https://github.com/OSU-Sustainability-Office/backup-killowatt-crackdown)
  - The backup ranking repo did not use a graph for calculating current usage, which is one way to get around the graph code's bugs, but not an ideal solution.

**Comment by solderq35** [comment]
I think we need [src/store/chart.module.js](https://github.com/OSU-Sustainability-Office/energy-dashboard/pull/216/files#diff-2d5a3060972003c001cad8e618851a95a85f651bdabad54138cbbe5f9dd46ae5) to check the building's name and (for example) calculate the graph logic differently for Weatherford, I don't think `src/store/chart_modifiers/line_bar/accumulated_real.js` shows the building name.

I was able to get the "main graph" by commenting out `await chartModifier.postGetData(chartData, reqPayload, this, store)` in `chart.module.js`, as it previously did not appear when I implemented rounding to nearest existing map key. 

Not sure how to proceed, maybe better to try index on the Weatherford data array next instead of map and keys.

**Comment by solderq35** [comment]
From my checking on `src/store/chart_modifers/index.js`, `accumulated_real.js` and `avg_accumulated_real.js` are called for the campaigns, but not `energy_change.js`. I think I will have to modify `avg_accumulated_real.js` next.

**Comment by solderq35** [comment]
Got the Weatherford data to kinda work without breaking the other buildings:

![](https://media.discordapp.net/attachments/1051648008594391077/1072681261665112094/image.png?width=1440&height=522)

Notes:
- Weatherford still doesn't work on the graph with all the buildings on it.
- Weatherford works for the graph with individual building data, but only for the "past 28 days", "past day" and "past 6 hours" show no data (due to insufficient data available?)
- Percentages are shown for all buildings now including Weatherford.
- I had to mess with the indices a bit to avoid causing errors, but this changed the percentage values (for example, Poling is -9.27% over on https://dashboard.sustainability.oregonstate.edu/#/campaign/8, but on the test build it is -8.95%)

**Comment by solderq35** [comment]
The math is also quite off from the backup kilowatt repo (https://github.com/OSU-Sustainability-Office/backup-killowatt-crackdown/tree/main/src), so I'm not sure what is correct here.
![image](https://user-images.githubusercontent.com/82061589/217406202-d0af95e4-5363-4113-839b-3f654e4c1b58.png)

- Change  `this.activeCampaign = campaigns[campaigns.length-4];` in line 90 of `src/App.vue` of that repo

**Comment by solderq35** [comment]
![image](https://user-images.githubusercontent.com/82061589/217624361-406e7b8d-b011-437a-ab77-fe3de8689e8d.png)

Not sure why there is a sudden drop off at the end, and the math in general for this needs audit, but I kind of got it working for the graph with all buildings on it.

It doesn't work for "past day" or "past 6 hours" for weatherford but after looking at this I think it's because there is a lack of data towards the end? Or a problem in our data sorting algorithm

**Comment by solderq35** [comment]
EDIT:
Employed hacky workaround to not show last data point for a given building if it is -100% on the graph with all buildings on it (cause probably bugged)

![](https://media.discordapp.net/attachments/1051648008594391077/1072955429035987056/image.png?width=1440&height=523)

![](https://media.discordapp.net/attachments/1051648008594391077/1072955776244666568/image.png?width=1440&height=485)

**Comment by solderq35** [comment]
Fixed Issue with the sidebar percentages being different from before.

![image](https://user-images.githubusercontent.com/82061589/217652480-d6673751-f2f4-4e59-ba06-ec0e59d26367.png)

**Comment by solderq35** [comment]
Summary of what file affects what for campaigns (non-exhaustive):
- Sidebar:
![image](https://user-images.githubusercontent.com/82061589/217697581-c7914556-2890-4468-a684-9401aecb5ef7.png)
  - [src/store/chart_modifiers/accumulated_real.js](https://github.com/OSU-Sustainability-Office/energy-dashboard/blob/weatherford-debug/src/store/chart_modifiers/line_bar/accumulated_real.js): Internal logic of calculating the "current usage" percentages.
    - Need tweaks to index values for Weatherford, round to nearest valid key value.
  - [src/store/chart_modifiers/avg_accumulated_real.js](https://github.com/OSU-Sustainability-Office/energy-dashboard/blob/weatherford-debug/src/store/chart_modifiers/line_bar/avg_accumulated_real.js): Internal logic of calculating the "baseline" percentages.
    - Seems to mostly work out of the box, don't need too many tweaks to index for Weatherford
  - [src/components/campaigns/campaign_building_list.vue](https://github.com/OSU-Sustainability-Office/energy-dashboard/blob/weatherford-debug/src/components/campaigns/campaign_building_list.vue): Actually displaying / sorting the data

- Individual Building Graph:
![image](https://user-images.githubusercontent.com/82061589/217699449-5fd6463c-349c-4680-8c29-53568510f80d.png)
  - [src/store/chart_modifiers/accumulated_real.js](https://github.com/OSU-Sustainability-Office/energy-dashboard/blob/weatherford-debug/src/store/chart_modifiers/line_bar/accumulated_real.js): Internal logic of calculating the "current usage" percentages.
    - Need tweaks to index values for Weatherford, round to nearest valid key value.
  - [src/store/chart_modifiers/avg_accumulated_real.js](https://github.com/OSU-Sustainability-Office/energy-dashboard/blob/weatherford-debug/src/store/chart_modifiers/line_bar/avg_accumulated_real.js): Internal logic of calculating the "baseline" percentages.
    - Seems to mostly work out of the box, don't need too many tweaks to index for Weatherford
  - [src/components/campaigns/campaign_building_list.vue](https://github.com/OSU-Sustainability-Office/energy-dashboard/blob/weatherford-debug/src/components/campaigns/campaign_building_list.vue): Actually displaying / sorting the data

- Graph with all the Buildings on it:
![image](https://user-images.githubusercontent.com/82061589/217698839-057bdc09-6ccb-440c-882c-51e132978349.png)
  - [src/store/chart_modifiers/baseline_perc.js](https://github.com/OSU-Sustainability-Office/energy-dashboard/blob/weatherford-debug/src/store/chart_modifiers/line_bar/baseline_perc.js)
    - Tweaks to index values for Weatherford needed (round to nearest valid key value)

**Comment by solderq35** [comment]
# Console.log Debug Locations Part 2
Will brain dump all the console.log locations before I forget which is which, then remove them from the branch so this is ready for merging.

Line numbers below will **hopefully** link to the correct line **in the files as they appeared in a specific commit**, when the log lines are still there. 
- **Do not check the files on the latest commit of the branch, these log lines will be removed by then!**

## src/store/block_modifiers/campaign_linebar.mod.js
- Covers ranking the buildings on leaderboard and displaying leaderboard data
- [Line 108](https://github.com/OSU-Sustainability-Office/energy-dashboard/blob/e663c82e3954f1660fc7aae9a0c92e69dd8944d1/src/store/block_modifiers/campaign_linebar.mod.js#L108)
  - Did checks for length of the baseline vs current data arrays - they should be the same length!

## src/store/chartmodule.js
- Responsible for calling every chart data type, whether it's for leaderboard, individual building, all buildings, etc.
- [Line 55](https://github.com/OSU-Sustainability-Office/energy-dashboard/blob/e663c82e3954f1660fc7aae9a0c92e69dd8944d1/src/store/chart.module.js#L55) (after chartData is initialized / defined)
  - Something I did to check for Weatherford specifically.
  - `console.log(chartData)`  - [gets Map Object data structure](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) (with key-value pairs) that includes information like building name as well as the meter data as an array inside the object.
![image](https://user-images.githubusercontent.com/82061589/217959441-de254cf0-c374-4a8d-9e14-d36237ca4485.png)
  - `console.log(chartData.data)` - gets Array of objects for the meter data; each object is a key-value pairing.
![image](https://user-images.githubusercontent.com/82061589/217960085-85cd5298-dc29-4f10-b373-994c8faab13f.png)
  - `await chartModifier.postGetData(chartData, reqPayload, this, store)` - this line is responsible for actually calling the chart logic files (`src/store/chart_modifiers/line_bar/accumulated_real.js` and `src/store/chart_modifiers/line_bar/baseline_perc.js`). If nonexistent values are found at this time by the chart logic files, this results in the data not being shown on the graph / leaderboard (e.g. for Weatherford past 6 hours, on http://localhost:8080/#/campaign/8)

## src/store/chart_modifiers/line_bar/accumulated_real.js
- Covers "current use" data for leaderboard / individual data graph
- [Line 38](https://github.com/OSU-Sustainability-Office/energy-dashboard/blob/e663c82e3954f1660fc7aae9a0c92e69dd8944d1/src/store/chart_modifiers/line_bar/accumulated_real.js#L38)
  - `console.log(resultDataObject)` - this basically just does the same thing as  `console.log(chartData)` in `src/store/chartmodule.js`.  Returns an Object with building name, meter data as an array inside the object, etc.
- [Line 74](https://github.com/OSU-Sustainability-Office/energy-dashboard/blob/e663c82e3954f1660fc7aae9a0c92e69dd8944d1/src/store/chart_modifiers/line_bar/accumulated_real.js#L74)
  - For debugging valid key values for the resultDataObject, more info [here](https://github.com/OSU-Sustainability-Office/energy-dashboard/issues/191#issuecomment-1414465741) on how to debug this.
- [Line 94](https://github.com/OSU-Sustainability-Office/energy-dashboard/blob/e663c82e3954f1660fc7aae9a0c92e69dd8944d1/src/store/chart_modifiers/line_bar/accumulated_real.js#L94)
  - Check keysarray, this is an array with all the valid keys in it that we use for making sure Weatherford shows valid data. Checking the keys array helps ensure that the key-rounding feature is working.
- [Line 113](https://github.com/OSU-Sustainability-Office/energy-dashboard/blob/e663c82e3954f1660fc7aae9a0c92e69dd8944d1/src/store/chart_modifiers/line_bar/accumulated_real.js#L113)
  - Checking if the non-Weatherford halls (not manual data entry) show the same key-value pairs as they did before (as they should).

## src/store/chart_modifiers/line_bar/avg_accumulated_real.js
- Covers "baseline" data for leaderboard / individual building graph
- Not much to say here, not much modifications needed here.
- [Line 115](https://github.com/OSU-Sustainability-Office/energy-dashboard/blob/e663c82e3954f1660fc7aae9a0c92e69dd8944d1/src/store/chart_modifiers/line_bar/avg_accumulated_real.js#L115)
  - `returnData` is an array of the meter values (baseline)

## src/store/chart_modifiers/line_bar/baseline_perc.js
- Covers "all buildings" graph
- [Line 144](https://github.com/OSU-Sustainability-Office/energy-dashboard/blob/e663c82e3954f1660fc7aae9a0c92e69dd8944d1/src/store/chart_modifiers/line_bar/baseline_perc.js#L144)
  - `returnData` is an array of the meter values (all buildings)

**Comment by solderq35** [comment]
Kind of audited math by asking Lety and Brandon (they said is fine).

Maybe still some UI issues but I'm not actively working on this at this point so I'll close issue. If we need to, I will re open with more specific Github Issue concerning graph UI etc
